### ISSUE TITLE
Issue with Django 2.1

### ISSUE THREAD

**Issue by shortc** [kstateome/django-cas#75]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'catalog_db.wsgi.application' could not be loaded; Error importing module.

Current error message when attempted running server. Reverted back to Django 2.0.6 and cas backend works properly again.

**Comment by ryanbagwell** [comment]
See #77 for a fix
